CREATE TABLE OFICINA(
COD_OFICINA NUMBER(3) NOT NULL CONSTRAINT PK_OFICINA PRIMARY KEY,
DIRECCION VARCHAR (40) NOT NULL,
TELEFONO NUMBER (9) NOT NULL,
DNI_DIR VARCHAR (9) NOT NULL,
DNI_COM VARCHAR (9) NOT NULL,
CONSTRAINT CK_OFICINA CHECK (LENGHT(TELEFONO)=9),
CONSTRAINT FK_DIRECTOR FOREIGN KEY(DNI_DIR) REFERENCES DIRECTOR(DNI)
);

CREATE TABLE COMERCIAL(
DNI NUMBER(3) NOT NULL CONSTRAINT PK_COMERCIAL PRIMARY KEY,
COD_OFICINA NUMBER (3) NOT NULL,
COMISION NUMBER (3) NOT NULL,
CONSTRAINT CK_COMISION CHECK (COMISION > 0 AND COMISION < 100)
);

ALTER TABLE OFICINA ADD (
CONSTRAINT FK_COMERCIAL FOREING KEY(DNI_COM) REFERENCES COMERCIAL(DNI)
);

ALTER TABLE COMERCIAL ADD (
CONSTRAINT FK_OFICINA1 FOREING KEY(COD_OFICINA) REFERENCES OFICINA(COD_OFICINA)
);

CREATE TABLE VENDEDOR(
DNI NUMBER(3) NOT NULL CONSTRAINT PK_VENDEDOR PRIMARY KEY,
COD_OFICINA NUMBER (3) NOT NULL,
TURNO VARCHAR (10) NOT NULL,
CONSTRAINT CK_TURNO CHECK (TURNO IN('MAÑANA','TARDE','NOCHE')),
CONSTRAINT FK_OFICINA2 FOREING KEY(COD_OFICINA) REFERENCES OFICINA(COD_OFICINA)
);