CREATE TABLE PROFESOR(
DNI VARCHAR (9) NOT NULL,
NOMBRE CHAR (20) NOT NULL,
AP1 CHAR (20) NOT NULL,
AP2 CHAR (20) NULL,
CONSTRAINT PK_PROFESOR PRIMARY KEY (DNI)
);

CREATE TABLE CICLOFORM (
CODCICLO VARCHAR (2) NOT NULL,
NOMBRE CHAR (20) NOT NULL,
TIPO CHAR (10) NOT NULL, 
CONSTRAINT PK_CODCICLO PRIMARY KEY (CODCICLO)
);

CREATE TABLE ASIGNATURA (
CODASIG VARCHAR (2) NOT NULL,
NOMBRE CHAR (20) NOT NULL,
NUMHORAS NUMBER (2) NOT NULL,
DNIPROF VARCHAR (9) NOT NULL,
CODCICLO VARCHAR (2) NOT NULL,
CONSTRAINT PK_ASIGNATURA PRIMARY KEY (CODASIG),
CONSTRAINT FK_PROFESOR FOREIGN KEY (DNIPROF) REFERENCES PROFESOR (DNI),
CONSTRAINT FK_CICLOFORM FOREIGN KEY (CODCICLO) REFERENCES CICLOFORM (CODCICLO)
);

CREATE TABLE IDIOMA(
CODIDIOMA VARCHAR (2) NOT NULL,
DESCRIPCION CHAR (20) NOT NULL,
CONSTRAINT PK_IDIOMA PRIMARY KEY (CODIDIOMA)
);

CREATE TABLE ALUMNO(
DNI VARCHAR (9) NOT NULL,
NOMBRE CHAR (20) NOT NULL,
AP1 CHAR (20) NOT NULL,
AP2 CHAR (20) NULL,
DIRECCION CHAR (50) NOT NULL,
EMAIL CHAR (30) NOT NULL,
TELEFONO NUMBER (9) NOT NULL,
CODIDIOMA VARCHAR (2) NOT NULL,
CONSTRAINT PK_ALUMNO PRIMARY KEY (DNI),
CONSTRAINT FK_IDIOMA FOREIGN KEY (CODIDIOMA) REFERENCES IDIOMA (CODIDIOMA)
);

CREATE TABLE MATRICULA(
DNIALUM VARCHAR (9) NOT NULL,
CODASIG VARCHAR (2) NOT NULL,
CONSTRAINT PK_MATRICULA PRIMARY KEY (DNIALUM, CODASIG),
CONSTRAINT FK_ALUMNO FOREIGN KEY (DNIALUM) REFERENCES ALUMNO (DNI),
CONSTRAINT FK_ASIGNATURA FOREIGN KEY (CODASIG) REFERENCES ASIGNATURA (CODASIG)
);

CREATE TABLE IDIOMASPROF(
CODIDIOMA VARCHAR (2) NOT NULL,
DNIPROF VARCHAR (9) NOT NULL,
CONSTRAINT PK_IDIOMASPROF PRIMARY KEY (CODIDIOMA,DNIPROF),
CONSTRAINT FK_IDIOMAS FOREIGN KEY (CODIDIOMA) REFERENCES IDIOMA (CODIDIOMA),
CONSTRAINT FK_PROFESORR FOREIGN KEY (DNIPROF) REFERENCES PROFESOR (DNI)
);

CREATE TABLE DATOS_PERSONALES(
DNI VARCHAR (9) NOT NULL CONSTRAINT PK_DATOS PRIMARY KEY,
NOMBRE CHAR (20) NOT NULL,
AP1 CHAR (20) NOT NULL,
AP2 CHAR (20) NULL
);

ALTER TABLE PROFESOR ADD CONSTRAINT FK_DNI_PROF FOREIGN KEY(DNI) REFERENCES DATOS_PERSONALES(DNI);
ALTER TABLE ALUMNO ADD CONSTRAINT FK_DNI_ALUM FOREIGN KEY(DNI) REFERENCES DATOS_PERSONALES(DNI);

ALTER TABLE PROFESOR DROP (NOMBRE);
ALTER TABLE PROFESOR DROP (AP1);
ALTER TABLE PROFESOR DROP (AP2);

ALTER TABLE ALUMNO DROP (NOMBRE);
ALTER TABLE ALUMNO DROP (AP1);
ALTER TABLE ALUMNO DROP (AP2);