CREATE TABLE DIRECTOR(
DNI_DIRECTOR VARCHAR(9) NOT NULL,
PRAPELLIDO VARCHAR(40) NOT NULL,
SGAPELLIDO VARCHAR(40) NULL,
DOMICILIO VARCHAR(50) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
EMAIL VARCHAR(100) NULL,
CONSTRAINT PK_DIRECTOR PRIMARY KEY(DNI_DIRECTOR)
);

CREATE TABLE SUPERMERCADO(
CODSUP NUMBER(3) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
SUPERFICIE NUMBER(5) NOT NULL,
ESALQUILER NUMBER(1) NOT NULL,
FECHA DATE NOT NULL,
DNI_DIRECTOR VARCHAR(9) NOT NULL,
CONSTRAINT PK_SUPERMERCADO PRIMARY KEY(CODSUP),
CONSTRAINT FK_DIRECTOR FOREIGN KEY(DNI_DIRECTOR) REFERENCES DIRECTOR(DNI_DIRECTOR),
CONSTRAINT CK_ESALQUILER CHECK(ESALQUILER BETWEEN 0 AND 1)
);

CREATE TABLE VENDEDOR(
DNI_VENDEDOR NUMBER(9) NOT NULL,
NOMBRE VARCHAR(40) NOT NULL,
PRAPELLIDO VARCHAR(40) NOT NULL,
SGAPELLIDO VARCHAR(40) NULL,
DOMICILIO VARCHAR(50) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
EMAIL VARCHAR(50) NULL,
CODSUP NUMBER(3) NOT NULL,
CONSTRAINT PK_VENDEDOR PRIMARY KEY(DNI_VENDEDOR),
CONSTRAINT FK_SUPERMERCADO FOREIGN KEY(CODSUP) REFERENCES SUPERMERCADO(CODSUP),
);

CREATE TABLE CLIENTE(
DNI_CLIENTE NUMBER(9) NOT NULL,
PRAPELLIDO VARCHAR(50) NOT NULL,
SGAPELLIDO VARCHAR(50) NULL,
DOMICILIO VARCHAR(50) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
EMAIL VARCHAR(50) NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI_CLIENTE)
);

CREATE TABLE VENTA(
CODVENTA NUMBER(9) NOT NULL,
FECHA DATE NOT NULL,
DNI_VENDEDOR NUMBER(9) NOT NULL,
DNI_CLIENTE NUMBER(9) NOT NULL,
CONSTRAINT PK_VENTA PRIMARY KEY(CODVENTA),
CONSTRAINT FK_VENDEDOR_1 FOREIGN KEY(DNI_VENDEDOR) REFERENCES VENDEDOR(DNI_VENDEDOR),
CONSTRAINT FK_CLIENTE_1 FOREIGN KEY(DNI_CLIENTE) REFERENCES CLIENTE(DNI_CLIENTE)
);

CREATE TABLE PRODUCTO(
CODPRODUCTO NUMBER(3) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
FAMILIA VARCHAR(100) NOT NULL,
GENERO VARCHAR(10) NOT NULL,
DESCUENTO NUMBER(1) NULL,
IVA NUMBER(3) NOT NULL,
CONSTRAINT PK_PRODUCTO PRIMARY KEY(CODPRODUCTO),
CONSTRAINT CK_DESCUENTO CHECK(DESCUENTO IN (0,1))
);

CREATE TABLE PRECIO(
FECHA DATE NOT NULL,
PRECIO NUMBER(10) NOT NULL,
CODPRODUCTO NUMBER(3) NOT NULL,
CONSTRAINT PK_PRECIO PRIMARY KEY(FECHA, CODPRODUCTO),
CONSTRAINT FK_PRECIO FOREIGN KEY(CODPRODUCTO) REFERENCES PRODUCTO(CODPRODUCTO)
);

CREATE TABLE LINEAVENTA(
NUMLINEA NUMBER(5) NOT NULL,
CANTIDAD NUMBER(10) NOT NULL,
CODVENTA NUMBER(3) NOT NULL,
CODPRODUCTO NUMBER(3) NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_LINEAVENTA PRIMARY KEY(CODVENTA, NUMLINEA),
CONSTRAINT FK_VENTA FOREIGN KEY(CODVENTA) REFERENCES VENTA(CODVENTA),
CONSTRAINT FK_PRODUCTO FOREIGN KEY(CODPRODUCTO) REFERENCES PRODUCTO(CODPRODUCTO),
CONSTRAINT FK_PRECIO FOREIGN KEY(FECHA) REFERENCES PRECIO(FECHA)
);

CREATE TABLE DEVOLUCION(
CODVENTA NUMBER(3) NOT NULL,
NUMLINEA NUMBER(5) NOT NULL,
FECHA DATE NOT NULL,
ESTADO NUMBER(1) NOT NULL,
TIPODEV VARCHAR(50) NOT NULL,
CONSTRAINT PK_DEVOLUCION PRIMARY KEY(FECHA, CODVENTA, NUMLINEA),
CONSTRAINT FK_LINEAVENTA FOREIGN KEY(NUMLINEA) REFERENCES LINEAVENTA(NUMLINEA),
CONSTRAINT FK_CODVENTA FOREIGN KEY(CODVENTA) REFERENCES VENTA(CODVENTA)
CONSTRAINT CK_ESTADO CHECK (ESTADO IN (1,0)),
);