CREATE TABLE TIPO_DP(
    COD_TIPO NUMBER 4 CONSTRAINT PK_TIPO PRIMARY KEY,
    DESCRIPCION VARCHAR 100 NOT NULL
);

ALTER TABLE DATOS_PERSONALES ADD CONSTRAINT FK_TIPO FOREIGN KEY (TIPO) REFERENCES TIPO_DP(COD_TIPO);

ALTER TABLE DIRECTOR ADD ANIOS NUMBER 2 NOT NULL;

ALTER TABLE COMERCIAL DROP COLUMN COMISION;

ALTER TABLE OFICINA ADD COMISION NUMBER 5 NOT NULL;

CREATE TABLE TURNO(
    COD_TURNO NUMBER 4 CONSTRAINT PK_TURNO PRIMARY KEY,
    DESCRIPCION VARCHAR 100 NOT NULL
);

ALTER TABLE VENDEDOR ADD CONSTRAINT FK_TURNO FOREIGN KEY (TURNO) REFERENCES TURNO(DESCRIPCION);

ALTER TABLE LIBRO DROP COLUMN TEMATICA;

CREATE TABLE TEMATICA_LIBRO(
    COD_TEM NUMBER 4 CONTRAINT PK_TEMATICA PRIMARY KEY,
    DESCRIPCION VARCHAR 100 NOT NULL
);

ALTER TABLE LIBRO ADD COD_TEM NUMBER 4;

ALTER TABLE LIBRO ADD CONSTRAINT FK_TEMATICA FOREIGN KEY (COD_TEM) REFERENCES TEMATICA_LIBRO(COD_TEM);