CREATE TABLE SEDE(
CODSEDE NUMBER(3) NOT NULL,
NOMBRE VARCHAR(40) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
CONSTRAINT PK_SEDE PRIMARY KEY(CODSEDE)
);

CREATE TABLE DEPARTAMENTO(
CODDEP NUMBER(3) NOT NULL,
NOMBRE VARCHAR(40) NOT NULL,
UBICACION VARCHAR(40) NOT NULL,
CONSTRAINT PK_DEPARTMENTO PRIMARY KEY(CODDEP, SEDE),
CONSTRAINT FK_SEDE FOREIGN KEY(CODSEDE) REFERENCES SEDE(CODSEDE)
);

CREATE TABLE PROGRAMADOR(
SECUENCIA VARCHAR(4) NOT NULL,
NOMBRE VARCHAR(40) NOT NULL,
AP1 VARCHAR(40) NOT NULL,
AP2 VARCHAR(40) NULL,
DIRECCION VARCHAR(50) NOT NULL,
CUENTA VARCHAR(19) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
TIPO VARCHAR(50),
CODDEP NUMBER(3) NOT NULL,
CODSEDE NUMBER(3) NOT NULL,
PROGMENTOR VARCHAR(4) NOT NULL,
CONSTRAINT PK_PROGRAMADOR PRIMARY KEY(SECUENCIA, CODDEP, CODSEDE),
CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY(CODDEP, CODSEDE) REFERENCES DEPARTAMENTO(CODDEP, CODSEDE),
CONSTRAINT FK_MENTOR FOREIGN KEY(PROGMENTOR, CODSEDE, CODDEP) REFERENCES PROGRAMADOR(SECUENCIA,CODSEDE,CODDEP)
);

CREATE TABLE EQUIPO(

);