
ALTER TABLE DATOSPERSONALES ADD CONSTRAINT CHECK(TIPO IN 'N','D');

ALTER TABLE DEPARTAMENTO ADD CONSTRAINT CHECK(NUMPROF BETWEEN 1 AND 30);
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT UN_DESCRIPCION UNIQUE (DESCRIPCION);

ALTER TABLE DOCTORANDO ADD CONSTRAINT CHECK(FECHA IN '1/1/2000' AND SYSDATE);

ALTER TABLE DOCTOR ADD CONSTRAINT UN_TITULO UNIQUE(TITULO);
ALTER TABLE DOCTOR ADD CONSTRAINT CHECK(LENGTH(TITULO) >= 10);
ALTER TABLE DOCTOR ADD CONSTRAINT CHECK (CALIFICACION >= 0 AND CALIFICACION <= 10);

ALTER TABLE CURSO ADD CONSTRAINT CHECK (DURACION >=10 AND DURACION <= 500);

/*EJERCICIO 4.12*/

ALTER TABLE AULAS ADD CONSTRAINT FK_AULAS FOREIGN KEY(CURSO) REFERENCES CURSO(CURSO);

CREATE TABLE DOCTORANDOCURSO(
CODDOCTOR NUMBER(3)NOT NULL,
CODCURSO NUMBER(3)NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_DOCTORANDOCURSO PRIMARY KEY(CODDOCTOR, CODCURSO),
CONSTRAINT FK_DOCTOR FOREIGN KEY(CODDOCTOR)REFERENCES DOCTOR(CODDOCTOR),
CONSTRAINT FK_CURSO FOREIGN KEY(CODCURSO)REFERENCES CURSO(CODCURSO)
);

ALTER TABLE AULA ADD CONSTRAINT CHECK(TIPO IN 'AULA DE PRACTICAS','AULA GRUPOS PEQUE�OS','AULA NORMAL','AULA MAGNA','AULA AUDIOVISUAL');